#* Original Properties

pull_sim_files_from_debug_folder: False
simulator_name: LumericalFDTD
simulator_dimension: 2D
simulator_max_wait_time: 3600
use_GUI_license: True
convert_existing: False
mesh_spacing_um: 0.1
use_smooth_blur: False
min_feature_size_um: 0.03
background_index: 1
min_device_index: 1
max_device_index: 1.52
init_permittivity_0_1_scale: 0.5
binarize_3_levels: False
do_normalize: False
voxel_size_x_um: 0.1
voxel_size_y_um: 0.1
voxel_size_z_um: 0.1
device_size_x_um: 100
device_size_y_um: 1
device_size_z_um: 30
device_vertical_minimum_um: 0
origin_displacement_um: [0, 0]
layering_axis: 2
num_layers: 10
num_spacers: 0
spacer_height_um: 0.51
spacer_density: 0
substrates_above_device: [{'name': 'glass_substrate', 'thickness_um': 2.5, 'material': 'SiO2 (Glass) - Palik'}]
num_sidewalls: 0
sidewall_material: etch
sidewall_extend_pml: False
sidewall_extend_focalplane: True
sidewall_thickness_um: 0.085
sidewall_vertical_minimum_um: -0.765
fdtd_simulation_time_fs: 600
boundary_conditions: pml
lum_mpi_exe: C:\Program Files (x86)\IntelSWToolsMPI\compilers_and_libraries_2020.4.321\windows\mpi\intel64\bin\mpiexec.exe
lum_solver_exe: C:\Program Files\Lumerical\v222\bin\fdtd-engine-impi.exe
lum_nprocs: 8
weight_by_individual_wavelength: True
use_gaussian_sources: True
use_airy_approximation: True
f_number: 2.2
airy_correction_factor: 0.84
beam_size_multiplier: 1
source_angle_theta_vacuum_deg: 0
source_angle_phi_deg: 0
xy_phi_rotations: [0, 90]
xy_adjtheta_rotations: [90, 0]
xy_names: ['x', 'y']
use_source_aperture: True
num_focal_spots: 2
adj_angles_theta_deg: [-30, 20]
dispersive_range_to_adjoint_src_map: [[0, 1, 2, 3]]
adjoint_src_to_dispersive_range_map: [0, 0, 0, 0]
add_infrared: False
lambda_min_um: 4.3
lambda_max_um: 4.7
lambda_min_eval_um: 4.2
lambda_max_eval_um: 4.8
lambda_center_um: 4.5
num_opt_dispersion_freqs: 5
dispersion_factors: {'adj_src_0x': 2, 'adj_src_1y': 2}
polarizations_focal_plane_map: [['x', 'y'], ['x', 'y'], ['x', 'y'], ['x', 'y']]
weight_focal_plane_map_performance_weighting: [1.0, 1.0, 1.0, 1.0]
weight_focal_plane_map: [1.0, 1.0, 1.0, 1.0]
do_green_balance: False
shuffle_green: False
polarization_name_to_idx: {'x': 0, 'y': 1, 'z': 2}
num_bands: 2
num_points_per_band: 15
desired_peaks_per_band_um: [0.475, 0.625]
explicit_band_centering: True
num_dispersive_ranges: 1
infrared_center_um: 0.94
do_rejection: False
softplus_kappa: 2
add_pdaf: False
pdaf_angle_phi_degrees: 45
pdaf_angle_theta_degrees: -8
pdaf_adj_src_idx: 0
enforce_xy_gradient_symmetry: False
weight_by_quadrant_transmission: True
total_num_iterations: 80
epoch_list: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80]
optimizer: AdamOptimizer
optimizer_settings: {'step_size': 0.01, 'betas': [0.9, 0.999], 'eps': '1e-8', 'moments': [0.0, 0.0]}
epoch_start_design_change_max: 0.15
epoch_end_design_change_max: 0.05
epoch_start_design_change_min: 0.05
epoch_end_design_change_min: 0
num_layers_per_epoch: False
fom_types: ['transmission', 'overall_transmission', 'intensity']
optimization_fom: intensity
reinterpolate_permittivity: True
reinterpolate_permittivity_factor: 2
reinterpolate_type: nearest
border_optimization: False
border_constant_width: 2
border_constant_density: 0
layer_gradient: False
flip_gradient: False
evaluate_bordered_extended: False
figures_of_merit: {'type': 'FoM', 'fom_func': null, 'grad_func': null, 'foms': {'fom_0_0': {'type': 'DispBSFoM', 'fom_func': null, 'grad_func': null, 'foms': {}, 'weights': [1.0], 'fwd_srcs': ['fwd_src_x'], 'fom_monitors': ['propagation_monitor', 'design_efield_monitor'], 'adj_srcs': ['adj_src_0x'], 'grad_monitors': ['propagation_monitor', 'design_efield_monitor'], 'polarization': 'TE', 'pos_max_freqs': [], 'neg_min_freqs': [], 'all_freqs': []}, 'fom_1_0': {'type': 'DispBSFoM', 'fom_func': null, 'grad_func': null, 'foms': {}, 'weights': [1.0], 'fwd_srcs': ['fwd_src_y'], 'fom_monitors': ['propagation_monitor', 'design_efield_monitor'], 'adj_srcs': ['adj_src_1y'], 'grad_monitors': ['propagation_monitor', 'design_efield_monitor'], 'polarization': 'TE', 'pos_max_freqs': [], 'neg_min_freqs': [], 'all_freqs': []}}, 'weights': [1.0, 1.0], 'fwd_srcs': [], 'fom_monitors': [], 'adj_srcs': [], 'grad_monitors': [], 'polarization': 'TE', 'pos_max_freqs': [], 'neg_min_freqs': [], 'all_freqs': []}
eval_source: periodic_plane
eval_boundary_conditions: auto
eval_normalize_against: input_power
eval_change_wavelength_range: True
eval_device_array_shape: [1, 1]


#
# Derived Properties - The below will overwrite any vars with the same name above.
#

#* Mesh Properties
#! TODO: Rewrite for blurring. ============================================================


min_feature_size_voxels: 0.3
blur_half_width_voxels: 0
#! ========================================================================================

#* Optical Properties
min_device_permittivity: 1
max_device_permittivity: 2.3104

#* Device Properties



device_size_z_um: 30

device_vertical_maximum_um: 30

device_voxels_x: 1000
device_voxels_y: 10
device_voxels_z: 300

device_mesh_voxels_x: 1001
device_mesh_voxels_y: 11

device_mesh_voxels_z: 302

# Borders
device_size_x_bordered_um: 100
device_size_y_bordered_um: 1
device_voxels_x_bordered: 1000
device_voxels_y_bordered: 10
device_mesh_voxels_x_bordered: 1001
device_mesh_voxels_y_bordered: 11
border_size_um: 0.5
border_size_voxels: 5

# Layers and Spacers

layer_height_um: 3.0
layer_height_voxels: 30

num_spacers: 0

focal_length_um: 15.0
focal_plane_center_vertical_um: -15.0


#* FDTD Properties

sim_edge_gap_z_um: 2.5
sim_edge_gap_x_um: 1.0
sim_edge_gap_y_um: 1.0

fdtd_size_z_um: 50.0


fdtd_size_x_um: 102.0
fdtd_size_y_um: 3.0

fdtd_region_maximum_z_um: 32.5

fdtd_region_minimum_z_um: -16.0

#* Surrounding Properties
pec_aperture_thickness_um: 0.30000000000000004
substrate_thickness_um: 
sidewall_x_positions_um: [50.0425, 0, -50.0425, 0]
sidewall_y_positions_um: [0, 0.5425, 0, -0.5425]
sidewall_xspan_positions_um: [0.085, 100.17, 0.085, 100.17]
sidewall_yspan_positions_um: [1.17, 0.085, 1.17, 0.085]

#* Spectral Properties
bandwidth_um: 0.40000000000000036
num_design_frequency_points: 5
num_eval_frequency_points: 30
lambda_values_um: [4.3, 4.4, 4.5, 4.6, 4.7]

max_intensity_by_wavelength: [24037.017006189533, 22956.841138659314, 21947.87379972565, 21003.990758244072, 20119.712288114275]

#! TODO: Rewrite for dispersive design materials. ===========================
dispersive_range_size_um: 0.40000000000000036
dispersive_ranges_um: [[4.3, 4.7]]
#! ==========================================================================

#* PDAF Functionality Properties
pdaf_focal_spot_x_um: 25.0
pdaf_focal_spot_y_um: 0.25
pdaf_lambda_min_um: 4.3
pdaf_lambda_max_um: 4.433333333333334
pdaf_lambda_values_um: [4.3, 4.333333333333333, 4.366666666666667, 4.4, 4.433333333333334]
pdaf_max_intensity_by_wavelength: [24037.017006189533, 23668.639053254443, 23308.664996212337, 22956.841138659314, 22612.923285657747]


#* Forward (Input) Source Properties
lateral_aperture_um: 110.00000000000001    #delete
src_maximum_vertical_um: 32.083333333333336
src_minimum_vertical_um: -15.75
mid_lambda_um: 4.5
gaussian_waist_radius_um: 1

source_angle_theta_rad: 0.0
source_angle_theta_deg: 0.0

# Inversion here from the adjoints' POV
adj_angles_theta_deg: [30, -20]
adj_angles_theta_rad: [0.5235987755982988, -0.3490658503988659]

#* Adjoint Source Properties
#! For arbitrary focal-point locations, this must be manually rewritten. ===========
adjoint_vertical_um: -15.0
num_adjoint_sources: 2

adjoint_x_positions_um: [25.0, -25.0, -25.0, 25.0]
adjoint_y_positions_um: [0.25, 0.25, -0.25, -0.25]
#! ==================================================================================

#* Optimization Properties

# [DEPRECATED] - Used for ensuring incremental change in standard gradient design ===============
epoch_range_design_change_max: 0.09999999999999999
epoch_range_design_change_min: 0.05


num_layers_per_epoch: [10]


## This is a mess
spectral_focal_plane_map: [[0, 15], [15, 30], [30, 45], [15, 30]]
desired_peak_location_per_band: [0, 0]
##

#* Evaluation Properties





eval_boundary_conditions: periodic




      

eval_lambda_min_um: 4.22
eval_lambda_max_um: 4.78




eval_fdtd_size_x_um: 100
eval_fdtd_size_y_um: 1
eval_fdtd_size_z_um: 16.5
eval_monitorbox_size_x_um: 100.67
eval_monitorbox_size_y_um: 1.67
eval_monitorbox_maximum_z_um: 30.5
eval_monitorbox_minimum_z_um: -0.5